from typing import List, Set



DAYS: List[str] = [
    "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
]
MONTHS: List[str] = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]
PLANETS: List[str] = [
    "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune",
]
ANIMAL_FAMILIES: List[str] = [
    "Mammal", "Fish", "Bird", "Reptile", "Amphibian", "Insect",
]
ANIMAL_EXAMPLES: List[str] = [
    "Cow", "Salmon", "Eagle", "Snake", "Frog", "Butterfly",
]
EXTRA_TOKENS: Set[str] = set(DAYS + MONTHS + PLANETS + ANIMAL_FAMILIES + ANIMAL_EXAMPLES)

SEMANTIC_CATEGORIES = {
    "Military & Conflict": [
        'War', 'war', 'military', 'forces', 'Army', 'Navy', 'Air', 'battle', 'attack', 'troops', 'weapons',
        'soldiers', 'army', 'victory', 'command', 'units', 'fleet', 'guns', 'Battle', 'Force', 'gun', 'invasion',
        'Regiment', 'artillery', 'capture', 'fired', 'Fleet', 'conflict', 'Operation', 'Admiral', 'Allied', 'arms',
        'bomb', 'tanks', 'SS', 'attacks', 'Squadron', 'Lieutenant', 'defensive', 'HMS', 'torpedo', 'Marine',
        'fighter', 'attacking', 'battleship', 'carrier', 'RAF', 'defended', 'bombers', 'Guard', 'Nazi', 'Colonel',
        'resistance', 'armed', 'landing', 'fought', 'commissioned', 'naval', 'Brigade', 'captain', 'pilot',
        'ammunition', 'targets', 'shells', 'alliance', 'patrol', 'armament', 'Confederate', 'ranks', 'flagship',
        'cavalry', 'submarine', 'Fort', 'bombs', 'armies', 'armored', 'armour', 'Allies', 'Defence', 'campaigns',
        'raids', 'reconnaissance', 'destroyers', 'garrison', 'combat', 'mission', 'Battalion', 'infantry', 'battalion',
        'Corps', 'commander', 'unit', 'Germans', 'U', 'defense', 'Chief', 'assault', 'battery', 'prisoners', 'enemy',
        'militia', 'surrender', 'retreat', 'convoy', 'flank', 'allies', 'turrets', 'turret', 'strategic', 'wounded',
        'killed', 'casualties', 'siege', 'opposition', 'offensive', 'threat', 'fighting', 'violence', 'occupation',
        'lieutenant', 'captured', 'secured', 'Commander', 'deployed', 'executed', 'firing', 'weapons', 'bombing',
        'commanded', 'destruction', 'medal', 'Medal', 'defences', 'defending', 'rebellion', 'aerial', 'withdrawal',
        'bases', 'fort', 'aboard', 'battleships'
    ],
    "Sports & Competition": [
        'game', 'season', 'team', 'games', 'match', 'player', 'players', 'League', 'Division', 'win', 'points',
        'race', 'playing', 'scored', 'field', 'runs', 'Cup', 'goal', 'league', 'football', 'Championship', 'score',
        'teams', 'winning', 'Club', 'fans', 'Game', 'tournament', 'championship', 'sports', 'matches', 'competition',
        'ball', 'hockey', 'innings', 'plays', 'basketball', 'NHL', 'baseball', 'Olympic', 'Olympics', 'cricket',
        'lap', 'stadium', 'Stadium', 'Bowl', 'NBA', 'WWE', 'wickets', 'playoffs', 'bowling', 'batting', 'pitch',
        'champion', 'NFL', 'FA', 'Wrestling', 'club', 'coach', 'winner', 'rival', 'quarterback', 'TNA', 'Bradman',
        'Champions', 'bat', 'Trophy', 'touchdown', 'penalty', 'defeating', 'assists', 'opponent', 'finals', 'squad',
        'races', 'match', 'final', 'ranked', 'professional', 'debut', 'Star', 'gold', 'Silver', 'bronze', 'beat',
        'compete', 'competed', 'contested', 'round', 'rounds', 'scoring', 'rating', 'Test', 'Giants', 'Yankees',
        'Arsenal', 'Championships', 'racing', 'athletic', 'athletes', 'tied', 'draw', 'loss', 'losses', 'World',
        'event', 'events', 'title', 'titles', 'sport', 'Hockey', 'Football', 'Baseball', 'Premier', 'Final',
        'Grand',
        'home',
        'away',
        'ranking', 'Top', 'medal', 'Medal', 'trophy', 'captain', 'manager', 'hosted', 'participated', 'qualified',
        'eliminated', 'UEFA', 'FIFA'
    ],
    "Music & Audio": [
        'album', 'song', 'music', 'single', 'band', 'record', 'songs', 'track', 'Music', 'studio', 'chart',
        'recording', 'sound', 'Award', 'artists', 'albums', 'guitar', 'performances', 'pop', 'records', 'vocals',
        'artist', 'concert', 'featuring', 'dance', 'musical', 'singer', 'radio', 'Billboard', 'lyrics', 'stars',
        'opera', 'composer', 'Song', 'singing', 'vocal', 'themes', 'awards', 'performing', 'piano', 'session',
        'charts', 'solo', 'bands', 'debut', 'soundtrack', 'producer', 'tracks', 'commercial', 'feature', 'voice',
        'contemporary', 'MTV', 'entitled', 'Singles', 'nomination', 'Rolling', 'Recording', 'Beatles', 'hip',
        'chorus', 'sounds', 'bass', 'jazz', 'rock', 'Madonna', 'Hot', 'Records', 'peaked', 'award', 'Harrison',
        'Dylan', 'Beyoncé', 'Gaga', 'Spears', 'Lennon', 'McCartney', 'Blues', 'punk', 'musician', 'musicians',
        'Grammy', 'instrumental', 'remix', 'label', 'audio', 'drums', 'instruments', 'performed', 'hit', 'hits',
        'played', 'play', 'live', 'Live', 'audience', 'review', 'reviews', 'critic', 'critics', 'criticism', 'praised',
        'popular', 'folk', 'tone', 'orchestra', 'concerts', 'mainstream', 'DJ',
        'rap', 
        'melody',
        'rhythm',
        'festival', 'tour', 'Tour', 'band', 'Band', 'guitarist', 'mix', 'recorded', 'titled', 'rock', 'Rock', 'released',
        'release', 'releases', 'rated', 'rating', 'gold', 'platinum', 'nominated', 'debuted', 'acclaim', 'collaboration'
    ],
    "Film, TV & Media": [
        'film', 'series', 'episode', 'show', 'video', 'television', 'production', 'story', 'characters', 'title',
        'scenes', 'popular', 'featured', 'critics', 'hit', 'director', 'cast', 'directed', 'screen', 'reception',
        'broadcast', 'DVD', 'movie', 'ratings', 'acting', 'actor', 'Academy', 'Film', 'viewers', 'starring',
        'theater', 'theatre', 'camera', 'Book', 'actress', 'Magazine', 'sequel', 'disc', 'literary', 'animated',
        'Rated', 'TV', 'host', 'character', 'storyline', 'writer', 'drama', 'comedy', 'aired', 'box',
        'content', 'media', 'script', 'Television', 'Media', 'protagonist', 'adaptation', 'fictional', 'Hollywood',
        'gameplay', 'Simpsons', 'Bond', 'Production', 'roles', 'Director', 'Award', 'Awards', 'Network', 'programme',
        'BBC', 'Disney', 'Fox', 'Series', 'Entertainment', 'footage', 'watching', 'news', 'newspaper', 'editor',
        'press', 'interview', 'publication', 'literature', 'books', 'novel', 'chapter', 'poet', 'poetry', 'dialogue',
        'Writing', 'writing', 'writes', 'author', 'article', 'text', 'words', 'notes', 'edition', 'writers', 'write',
        'meaning', 'readers', 'poem', 'poems', 'ISBN', 'magazine', 'comics',
        'narrative', 'plot', 'Plot', 'scene', 'channel', 'Channel', 'showed', 'view', 'viewed', 'appearance',
        'appearances', 'appearing', 'appeared', 'image', 'images', 'visual', 'graphics', 'animation', 'documentary',
        'program', 'programs', 'network', 'Network', 'online', 'website', 'IGN', 'review', 'reviews', 'critic', 'criticism',
        'premiered', 'premiere', 'finale', 'pilot', 'guest', 'Star', 'film', 'filming', 'filmed', 'performance',
        'performances', 'performing', 'perform', 'show', 'shows', 'shown', 'display', 'audience', 'video', 'Video'
    ],
    "Politics & Government": [
        'government', 'National', 'political', 'public', 'state', 'States', 'President', 'Court', 'election', 'party',
        'law', 'Congress', 'Minister', 'committee', 'capital', 'Department', 'federal', 'policy', 'officials',
        'Parliament', 'executive', 'treaty', 'Senate', 'governor', 'Governor', 'authority', 'vote', 'administration',
        'Republican', 'Commission', 'authorities', 'Board', 'Prime', 'council', 'Democratic', 'tax', 'legislation',
        'Federal', 'judge', 'chairman', 'courts', 'Vice', 'colonial', 'Federation', 'Treaty', 'policies', 'USA',
        'Ministry', 'Nations', 'votes', 'commission', 'minister', 'presidential', 'Constitution', 'elections', 'Power',
        'Commonwealth', 'Labour', 'alliance', 'conservative', 'UN', 'civilian', 'Rights', 'secretary', 'legislature',
        'Community', 'decisions', 'Defence', 'Government', 'Post', 'candidates', 'resolution', 'affairs', 'Crown',
        'poll', 'illegal', 'Assembly', 'department', 'intelligence', 'freedom', 'laws', 'Justice', 'debate',
        'opposition', 'Act', 'Soviet', 'social', 'national', 'Senator', 'Party', 'Council', 'Bureau', 'affairs',
        'order', 'rule', 'rights', 'campaign', 'campaigns', 'independence', 'political', 'politics', 'candidate',
        'voted', 'elected', 'appointed', 'leader', 'leaders', 'reform', 'bill', 'draft', 'rejected', 'approved',
        'passed', 'Supreme', 'Court', 'office', 'official', 'officially', 'agency', 'represent', 'representative',
        'representing', 'diplomatic',
        'ambassador', 
        'mayor', 'domestic', 'foreign', 'international', 'Union', 'sanctions',
        'referendum',
        'parliamentary',
        'municipal',
        'policy', 'policies', 'legislation', 'administration', 'nomination', 'hearing', 'ruling', 'decree'
    ],
    "Geography & Places": [
        'York', 'area', 'city', 'North', 'South', 'world', 'north', 'south', 'England', 'City', 'London', 'West',
        'River', 'east', 'town', 'country', 'west', 'Australia', 'State', 'land', 'County', 'Park', 'Road', 'France',
        'region', 'Europe', 'island', 'Route', 'highway', 'southern', 'Canada', 'San', 'California', 'northern',
        'Island', 'UK', 'Indian', 'coast', 'Britain', 'western', 'Virginia', 'High', 'eastern', 'Los', 'Spanish',
        'river', 'Hill', 'Pacific', 'Atlantic', 'Florida', 'Lake', 'Texas', 'Bay', 'village', 'Sea', 'Africa',
        'Center', 'Highway', 'Russian', 'St', 'Angeles', 'park', 'Central', 'Earth', 'Michigan', 'Wales', 'Mexico',
        'centre', 'capital', 'Scotland', 'Creek', 'Manchester', 'Boston', 'port', 'Latin', 'Oxford', 'Louis', 'square',
        'Italy', 'Saint', 'Museum', 'Ireland', 'Paris', 'Line', 'Green', 'county', 'cities', 'Valley', 'district',
        'border', 'Carolina', 'Polish', 'Home', 'Islands', 'Pennsylvania', 'routes', 'mountain', 'Indiana', 'Beach',
        'zone', 'Rome', 'Ohio', 'Cambridge', 'Philadelphia', 'Russia', 'Ocean', 'Liverpool', 'Columbia', 'Square',
        'Asia', 'Port', 'Francisco', 'Town', 'Office', 'Coast', 'Gulf', 'Hollywood', 'sites', 'waters', 'Kentucky',
        'Point', 'Station', 'Airport', 'Massachusetts', 'Lincoln', 'Mount', 'Cape', 'Poland', 'freeway', 'Sydney',
        'settlement', 'Van', 'Maryland', 'lands', 'province', 'Toronto', 'Sweden', 'Kong', 'Netherlands', 'Forest',
        'Temple', 'Jordan', 'Croatian', 'Puerto', 'Sound', 'Centre', 'lake', 'Houston', 'Federal', 'Swedish',
        'Berlin', 'Detroit', 'Melbourne', 'Asian', 'Israel', 'Land', 'Turkish', 'Greece', 'Austria', 'Tower',
        'Baltimore', 'Colorado', 'residential', 'Lane', 'valley', 'Somerset', 'shore', 'Miami', 'Seattle', 'Iowa',
        'Alabama', 'USA', 'Caribbean', 'Canal', 'Hungary', 'Lawrence', 'Australians', 'Belgium', 'Diego', 'Township',
        'Garden', 'villages', 'Country', 'Manhattan', 'Peninsula', 'Kansas', 'Wall', 'Hotel', 'Area', 'situated',
        'railroad', 'beach', 'Egyptian', 'Mississippi', 'Tennessee', 'Montreal', 'Philippines', 'Missouri', 'Hong',
        'rivers', 'mountains', 'Arizona', 'Indies', 'Persian', 'ocean', 'parish', 'inland', 'Switzerland', 'Oklahoma',
        'Austrian', 'Iraq', 'palace', 'Delaware', 'Edge', 'Denmark', 'Atlanta', 'Tokyo', 'Rico', 'Abbey', 'mainland',
        'Birmingham', 'Ridge', 'counties', 'Railroad', 'Hills', 'ports', 'banks', 'pit', 'strip', 'Hudson',
        'Madagascar', 'Connecticut', 'Phoenix', 'Ontario', 'Juan', 'Canterbury', 'Vancouver', 'Mountains', 'Drive',
        'Pearl', 'chapel', 'landscape', 'territory', 'territories', 'areas', 'location', 'locations', 'site', 'place',
        'places', 'abroad',
        'overseas', 'local', 'regional', 'national', 'international', 'worldwide', 'nearby', 'adjacent', 'surrounding',
        'Mediterranean', 'China', 'Japan', 'Korea', 'Vietnam', 'Norway', 'Cuba', 'Egypt', 'Spain', 'Germany', 'India',
        'New', 'York', 'States', 'American', 'British', 'French', 'German', 'English', 'Japanese', 'Australian',
        'European', 'Canadian', 'Indian', 'Spanish', 'Chinese', 'Roman', 'Russian', 'Italian', 'Scottish', 'Welsh',
        'Irish', 'Dutch', 'Polish', 'Swedish', 'Asian', 'Turkish', 'Greek', 'Austrian', 'Korean', 'Norwegian', 'Mexican',
        'Vietnamese', 'Arab', 'Portuguese', 'Hungarian', 'Croatian', 'Swiss',
        'African', 'Latin', 'Byzantine', 'Ottoman'
    ],
    "Transportation & Travel": [
        'km', 'ship', 'ships', 'aircraft', 'ft', 'miles', 'Road', 'route', 'feet', 'road', 'station', 'h', 'mph',
        'highway', 'crew', 'Port', 'fleet', 'vehicles', 'transport', 'Railway', 'railway', 'train', 'trains', 'cars',
        'car', 'plane', 'flight', 'airport', 'boat', 'kilometres', 'roads', 'landing', 'crossing', 'gas', 'seat',
        'interchange', 'street', 'deck', 'intersection', 'motion', 'launch', 'lap', 'Station', 'bridge', 'Bridge',
        'traffic', 'port', 'distance', 'track', 'tracks', 'bus', 'rail', 'vessels', 'passengers', 'journey', 'sailed',
        'Channel', 'convoy', 'driver', 'shipping', 'merchant', 'drivers', 'Railroad', 'delivery', 'ports', 'mobile',
        'elevation', 'strip', 'overseas', 'cargo', 'patrol', 'flagship', 'cruiser', 'vehicle', 'travel', 'travelled',
        'travels', 'trip', 'carrier', 'fly', 'flew', 'flying', 'engines', 'engine', 'fuel', 'steam', 'radar', 'drive',
        'driving', 'Route', 'Highway', 'Avenue', 'Street', 'Lane', 'Canal', 'aboard', 'transit'
    ],
    "Time, Numbers & Measurement": [
        'first', 'two', 'time', 'later', 'three', 'years', 'year', 'second', 'number', 'four', 'early', 'day',
        'million', 'end', 'September', 'August', 'long', 'October', 'May', 'five', 'century', 'June', 'high', 'July',
        'November', 'since', 'April', 'March', 'large', 'December', 'much', 'January', 'third', 'final', 'six',
        'February', 'next', 'last', 'late', 'days', 'half', 'period', 'II', 'point', 'old', 'less', 'months',
        'previous', 'week', 'eight', 'low', 'seven', 'various', 'throughout', 'little', 'full', 'level', 'mm', 'age',
        'ten', 'weeks', 'fourth', 'least', 'average', 'mi', 'hours', 'mid', 'earlier', 'minutes', 'highest', 'month',
        'increased', 'list', 'nine', 'beginning', 'lower', 'additional', 'length', 'percent', 'speed', 'date', 'size',
        'overall', 'nearly', 'higher', 'fifth', 'copies', 'extended', 'Since', 'increase', 'minute', 'initial',
        'respectively', 'numerous', 'prior', 'numbers', 'finally', 'smaller', 'Year', 'hour', 'listed', 'upper',
        'rate', 'middle', 'standard', 'annual', 'levels', 'peak', 'twenty', 'ending', 'mass', 'inches', 'metres',
        'yard', 'amount', 'rating', 'maximum', 'scale', 'mainly', 'seconds', 'recent', 'sixth', 'seasons', 'kg',
        'quarter', 'decade', 'hundred', 'lb', 'knots', 'meters', 'UTC', 'dates', 'typical', 'decades', 'eighth',
        'flat', 'depth', 'rank', 'oldest', 'basic', 'widespread', 'decline', 'measure', 'thousands', 'thirty', 'pace',
        'diameter', 'pounds', 'lowest', 'weekend', 'finale', 'platinum', 'ranking', 'rates', 'minimum', 'medium',
        'dollars', 'degrees', 'cent', 'percentage', 'USD', 'forty', 'tenth', 'measured', 'fifty', 'fastest', 'tall',
        'height', 'slow', 'brief', 'twelve', 'extensive', 'seventh', 'commonly', 'centuries', 'mile', 'intensity',
        'currently', 'rise', 'rapidly', 'temperature', 'fast', 'rare', 'significantly', 'roughly', 'semi', 'thick',
        'briefly', 'complete', 'temporary', 'ninth', 'rapid', 'afterwards', 'longest', 'formerly', 'apparently',
        'thereafter', 'repeated', 'eventually', 'especially', 'Instead', 'specifically', 'ago', 'Today', 'recently',
        'simultaneously', 'Often', 'still', 'always', 'immediately', 'largely', 'occasionally', 'regularly', 'otherwise',
        'greatly', 'somewhat', 'else', 'Usually', 'sometimes', 'never', 'likely', 'probably', 'whether', 'frequently',
        'typically', 'consecutive', 'newly', 'increasing', 'gradually', 'mostly', 'subsequently', 'rarely',

    ],
    "Science, Nature & Environment": [
        'species', 'water', 'storm', 'tropical', 'air', 'plants', 'animals', 'hurricane', 'climate', 'weather', 'fire',
        'trees', 'rainfall', 'environments', 'genus', 'Ocean', 'forest', 'bird', 'steam', 'mountain', 'Beach', 'coast',
        'surface', 'soil', 'fish', 'planet', 'Earth', 'ocean', 'sea', 'wild', 'flow', 'moon', 'prey', 'eggs', 'solar',
        'nest', 'rivers', 'bear', 'snow', 'Ice', 'typhoon', 'flood', 'diet', 'bones', 'insects', 'landscape', 'habitat',
        'wood', 'iron', 'carbon', 'coal', 'gas', 'nuclear', 'oxygen', 'DNA', 'chemical', 'energy', 'material', 'food',
        'oil', 'metal', 'research', 'effect', 'system', 'systems', 'technology', 'protein', 'genetic', 'theory', 'analysis',
        'formula', 'Science', 'scientific', 'computer', 'digital', 'electronic', 'concrete', 'machine', 'engine',
        'engines', 'fuel', 'battery', 'power', 'electric', 'cell', 'cells', 'structure', 'elements', 'characteristics',
        'process', 'evidence', 'data', 'study', 'studies', 'test', 'tests', 'specimens', 'observations', 'method',
        'technique', 'factor', 'model', 'models', 'impact', 'results', 'discovery', 'development', 'evolution',
        'occurred', 'physical', 'natural', 'environmental', 'global', 'heat', 'pressure', 'speed', 'weight', 'volume',
        'temperature', 'temperatures', 'rain', 'winds', 'cyclone', 'landfall', 'waves', 'atmosphere', 'space', 'orbit',
        'satellite', 'planets', 'Moon', 'Mars', 'Jupiter', 'Sun', 'light', 'dark', 'white', 'black', 'red', 'blue',
        'green', 'yellow', 'brown', 'grey', 'color', 'colour', 'image', 'visual', 'shape', 'pattern', 'patterns',
        'form', 'body', 'bodies', 'organ', 'stem', 'roots', 'fruit', 'plant', 'tree', 'animal', 'dog', 'horse',
        'horses', 'birds', 'shark', 'breed', 'breeding', 'classification', 'classified', 'acid', 'convection',
        'subspecies', 'atoms', 'molecules','gravity','biology','chemistry','physics','geology','astronomy','meteorology',
        'ecology','radiation','magnetic','volcano','earthquake','fossil','mineral','rock', 'stone', 'sand','cloud','lightning','thunder'
    ],
    "People, Society & Roles": [
        'people', 'family', 'men', 'members', 'school', 'father', 'man', 'children', 'women', 'population', 'wife',
        'mother', 'love', 'relationship', 'human', 'groups', 'art', 'social', 'person', 'female', 'community', 'king',
        'students', 'daughter', 'married', 'movement', 'language', 'personal', 'Christian', 'woman', 'friend', 'child',
        'majority', 'Queen', 'Lord', 'God', 'singer', 'individual', 'friends', 'education', 'male', 'depression',
        'religious', 'artist', 'culture', 'Society', 'Prince', 'award', 'parents', 'actor', 'royal', 'society',
        'author', 'chief', 'officials', 'Americans', 'residents', 'King', 'Emperor', 'Duke', 'Earl', 'Sir', 'Lady',
        'Princess', 'Bishop', 'Pope', 'leader', 'leaders', 'manager', 'professional', 'teacher', 'student', 'writer',
        'writers', 'authors', 'poet', 'editor', 'journalist', 'historian', 'scholars', 'scientists', 'workers', 'staff',
        'personnel', 'employees', 'citizens', 'humans', 'adult', 'adults', 'baby', 'boy', 'girl', 'boys', 'girls',
        'males', 'females', 'gay', 'families', 'husband', 'brother', 'sister', 'ethnic', 'identity', 'background',
        'birth', 'native', 'Catholic', 'Jewish', 'Muslim', 'Hindu', 'belief', 'faith', 'spiritual', 'moral', 'worship',
        'ceremony', 'ritual',
        'tradition', 'traditional', 'customs',
        'marriage', 'wedding', 'funeral', 'divorce',
        'youth', 'teenager',
        'elderly',
        'neighbor',
        'colleague', 'colleagues', 'partner', 'opponent', 'rival', 'ally', 'enemy', 'friend', 'friends', 'peer',
        'master', 'slave', 'slaves', 'owner', 'tenant',
        'landlord',
        'citizen', 'subject', 'immigrant',
        'refugee', 
        'tourist',
        'visitor', 'visitors', 'crowd', 'audience', 'public', 'private', 'civilian', 'consumer',
        'producer', 'creator', 'designer', 'engineer', 'architect', 'doctor', 'nurse',
        'patient',
        'lawyer',
        'judge', 'police', 'officer', 'soldier', 'sailor',
        'worker', 'labor', 'employee', 'employer',
        'boss',
        'assistant', 'volunteer',
        'expert',
        'novice',
        'hero', 'villain'
    ],
    "Proper names": [
        'John', 'New', 'United', 'States', 'American', 'British', 'World', 'May', 'York', 'US', 'North',
        'South', 'French', 'German', 'England', 'City', 'London', 'II', 'King', 'University', 'West',
        'James', 'Army', 'William', 'League', 'America', 'Division', 'County', 'Japanese', 'George',
        'Street', 'Australian', 'David', 'Royal', 'House', 'France', 'Michael', 'Henry', 'Washington',
        'Robert', 'Europe', 'Battle', 'Music', 'Japan', 'President', 'First', 'European', 'Cup', 'Navy',
        'Charles', 'Kingdom', 'Thomas', 'Canada', 'International', 'San', 'Paul', 'California', 'Union',
        'Great', 'Company', 'Award', 'Germany', 'India', 'Court', 'Island', 'Times', 'Smith', 'Hall',
        'College', 'UK', 'White', 'Indian', 'Awards', 'Peter', 'Black', 'Western', 'Church', 'Force',
        'Richard', 'Britain', 'C', 'NY', 'Championship', 'Star', 'High', 'Party', 'Association', 'Soviet',
        'Club', 'Chicago', 'Jackson', 'Edward', 'Act', 'Hill', 'Council', 'Johnson', 'History', 'Pacific',
        'Grand', 'Billboard', 'Atlantic', 'Christian', 'Florida', 'Game', 'Lake', 'Texas', 'Roman', 'Brown',
        'Bay', 'Day', 'Mary', 'Sea', 'Canadian', 'Queen', 'Africa', 'Love', 'Lord', 'Center', 'Highway',
        'Russian', 'St', 'Angeles', 'God', 'Central', 'Empire', 'Year', 'Jack', 'Italian', 'Michigan',
        'Wales', 'Martin', 'Group', 'TV', 'Madonna', 'Scotland', 'Jones', 'Greek', 'Old', 'Department',
        'Zealand', 'Three', 'Infantry', 'Service', 'Creek', 'Records', 'Fox', 'Rock', 'Committee', 'Prince',
        'Stone', 'Manchester', 'Tom', 'Harrison', 'Williams', 'Southern', 'Hurricane', 'Boston', 'Captain',
        'Oxford', 'Louis', 'Academy', 'BBC', 'Frank', 'Italy', 'Saint', 'Americans', 'Brigade', 'R', 'Fort',
        'Sun', 'Museum', 'Ireland', 'Paris', 'Lee', 'Line', 'Green', 'Joseph', 'Victoria', 'News', 'Live',
        'Valley', 'Stephen', 'Parliament', 'Cross', 'Football', 'Northern', 'Carolina', 'Homer', 'District',
        'Fantasy', 'Government', 'Post', 'Duke', 'Super', 'Studios', 'Polish', 'Senate', 'Home', 'Governor',
        'Taylor', 'Catholic', 'Alexander', 'Wilson', 'Joe', 'Festival', 'Pennsylvania', 'Islands', 'Civil',
        'Spain', 'Jersey', 'Mike', 'Harry', 'Show', 'Castle', 'Tech', 'Storm', 'Chart', 'Bond', 'Irish',
        'Institute', 'Elizabeth', 'Republican', 'Blue', 'Doctor', 'Georgia', 'Ohio', 'Cambridge',
        'Philadelphia', 'Commission', 'Arthur', 'Song', 'Middle', 'Russia', 'Board', 'Liverpool', 'Nintendo',
        'Columbia', 'Square', 'Andrew', 'Asia', 'Lieutenant', 'Port', 'Development', 'People', 'Jewish',
        'Prime', 'V', 'Long', 'Carey', 'Bob', 'Town', 'Office', 'PlayStation', 'HMS', 'Conference',
        'Anderson', 'Miller', 'Order', 'Brian', 'Railway', 'Emperor', 'Light', 'System', 'Art', 'Walter',
        'Coast', 'NHL', 'MD', 'Gulf', 'Lewis', 'Grant', 'Democratic', 'Davis', 'Hollywood', 'E', 'Disney',
        'Night', 'Daily', 'Women', 'El', 'Beyoncé', 'Field', 'Colonel', 'Supreme', 'Lady', 'Kentucky',
        'Point', 'Jean', 'Al', 'Olympics', 'Lincoln', 'Law', 'Station', 'Clark', 'Simpsons', 'Earl', 'Press',
        'IV', 'Songs', 'Public', 'Ottoman', 'L', 'Vietnam', 'Mount', 'Cape', 'Poland', 'Sydney', 'Van',
        'Imperial', 'Maryland', 'Special', 'Arts', 'Moore', 'Mulder', 'MTV', 'Gordon', 'Stadium', 'Golden',
        'Ben', 'Bank', 'Radio', 'Justice', 'Summer', 'Tony', 'Egypt', 'Way', 'SS', 'Adams', 'Critical',
        'Sam', 'IGN', 'Hamilton', 'Rome', 'Memorial', 'Kennedy', 'Military', 'Plot', 'Indiana', 'Sunday',
        'Howard', 'Beach', 'Scully', 'Dark', 'Five', 'Hitler', 'Video', 'Revolution', 'Science', 'Wars',
        'Magazine', 'WWE', 'Ryan', 'Rolling', 'Weekly', 'Assembly', 'Mountain', 'Douglas', 'Andy', 'Arsenal',
        'Family', 'Kevin', 'Kent', 'Mediterranean', 'Beatles', 'Bruce', 'Matt', 'Stanley', 'K', 'Director',
        'Bristol', 'Adam', 'Philip', 'Mexican', 'Channel', 'Korea', 'Ten', 'Lisa', 'Fame', 'Project',
        'Robinson', 'Oregon', 'Television', 'Construction', 'Norman', 'Nelson', 'Media', 'Patrick',
        'Premier', 'Nations', 'Byzantine', 'Sweden', 'Men', 'Netherlands', 'Francis', 'Moon', 'Morgan',
        'Bush', 'Jews', 'Jeff', 'Ray', 'Girl', 'Space', 'Marine', 'Welsh', 'Temple', 'Jordan', 'Croatian',
        'Le', 'Anne', 'De', 'Thompson', 'Puerto', 'Kelly', 'Russell', 'Sound', 'Allen', 'Gold', 'Bishop',
        'Hungarian', 'Command', 'Six', 'Centre', 'Constitution', 'Parker', 'Batman', 'Wright', 'Max',
        'Carter', 'Power', 'FA', 'Library', 'Arab', 'Jane', 'Education', 'Rose', 'Eric', 'Palace',
        'Commander', 'Houston', 'Federal', 'Morris', 'Ross', 'Ford', 'Bell', 'Commonwealth', 'Maria', 'Main',
        'Indians', 'Santa', 'Corporation', 'Simpson', 'Warner', 'Jason', 'Gaga', 'DE', 'Wood', 'RAF',
        'Spears', 'Jesus', 'NBC', 'Nielsen', 'Last', 'Network', 'Asian', 'Jay', 'Vice', 'Xbox', 'Clinton',
        'Stewart', 'End', 'Alex', 'Sports', 'Knight', 'Land', 'Turkish', 'Iron', 'Sarah', 'Lennon', 'Brazil',
        'Greece', 'Austria', 'Tower', 'Albums', 'H', 'Baltimore', 'Evans', 'Holy', 'Samuel', 'Foundation',
        'Tim', 'Lane', 'Band', 'Mario', 'Abbey', 'Perry', 'ABC', 'Jimmy', 'Business', 'PA', 'Sony', 'Nixon',
        'Rico', 'Johnny', 'Yankees', 'Edwards', 'Kurt', 'Ward', 'Dream', 'Apple', 'Ridge', 'Human', 'Obama',
        'Silver', 'Hills', 'Dead', 'Hudson', 'Rachel', 'Wayne', 'Madagascar', 'Connecticut', 'Bobby',
        'Phoenix', 'McCartney', 'Morrison', 'Nine', 'Rights', 'Key', 'Juan', 'Universal', 'VI', 'Friday',
        'CR', 'Canterbury', 'Todd', 'Community', 'Allies', 'Defence', 'Baby', 'Ken', 'DC', 'UEFA', 'Trust',
        'Napoleon', 'Gary', 'Dragon', 'Vancouver', 'Hugh', 'Phil', 'Review', 'Mountains', 'Drive', 'Pearl',
        'TNA', 'Bradman', 'Angel', 'Champions', 'Foreign', 'Trophy', 'Dwight', 'Alice', 'Peace', 'Guardian',
        'Legacy', 'Hockey', 'Benjamin', 'Franklin', 'Walker', 'Wing', 'Country', 'Matthew', 'Roosevelt',
        'Dave', 'Kansas', 'Mars', 'Head', 'Wall', 'Building', 'Carl', 'N', 'Hotel', 'Digital', 'USS', 'Ron',
        'Guy', 'Area', 'Khan', 'Sullivan', 'Halo', 'Campbell', 'Mississippi', 'Tennessee', 'Crown',
        'Montreal', 'Pop', 'Ann', 'Margaret', 'Depression', 'Philippines', 'Race', 'Heart', 'Missouri',
        'Historic', 'Front', 'Billy', 'Born', 'Critics', 'Blues', 'Hong', 'Independent', 'Health', 'Warren',
        'Free', 'Graham', 'Alfred', 'Mitchell', 'Cuba', 'Water', 'Files', 'Arizona', 'Open', 'Indies',
        'Persian', 'Guide', 'Dylan', 'Marie', 'Confederate', 'Seven', 'Murphy', 'Harvey', 'Switzerland',
        'Broadway', 'Hero', 'Go', 'Oklahoma', 'Austrian', 'UN', 'Federation', 'Iraq', 'Delaware', 'Edge',
        'Ed', 'Shakespeare', 'Original', 'VII', 'Leslie', 'Album', 'Denmark', 'Jonathan', 'Atlanta',
        'Players', 'Ice', 'Rihanna', 'Tokyo', 'Baseball', 'Jon', 'Amy', 'Arnold', 'Keith', 'Prize', 'Raw',
        'Tracy', 'Birmingham', 'Enterprise', 'Roy', 'Works', 'Windows', 'Outstanding', 'Hindu', 'Jupiter',
        'Administration', 'Minnesota', 'Manhattan', 'Portland', 'Tamil', 'Bureau', 'Lost', 'Marshall',
        'Player', 'Christ', 'Cooper', 'Gilbert', 'Journal', 'Treaty', 'Horse', 'Iowa', 'Dan', 'Design',
        'Alabama', 'Charlie', 'Fire', 'Back', 'Canal', 'Ministry', 'Ian', 'Hungary', 'Lawrence', 'Story',
        'G', 'Australians', 'Belgium', 'Trek', 'Diego', 'Nick', 'Township', 'Senator', 'Children', 'Garden',
        'Track', 'Christopher', 'Vietnamese',
    ],
"Verbs":[
    'would', 'made', 'used', 'became', 'including', 'said', 'known', 'could', 'began', 'work',
    'released', 'called', 'found', 'took', 'use', 'following', 'received', 'played', 'wrote',
    'described', 'led', 'named', 'make', 'built', 'held', 'considered', 'moved', 'become', 'take',
    'written', 'though', 'given', 'gave', 'returned', 'went', 'published', 'produced', 'lost', 'stated',
    'attack', 'include', 'recorded', 'using', 'making', 'died', 'run', 'developed', 'reported', 'felt',
    'noted', 'announced', 'reached', 'created', 'sent', 'return', 'win', 'seen', 'followed', 'performed',
    'served', 'killed', 'taken', 'established', 'appeared', 'caused', 'started', 'added', 'sold', 'formed',
    'located', 'completed', 'playing', 'opened', 'saw', 'worked', 'get', 'scored', 'born', 'provided',
    'featured', 'see', 'allowed', 'working', 'wanted', 'placed', 'put', 'go', 'joined', 'believed',
    'replaced', 'designed', 'finished', 'start', 'saying', 'forced', 'shot', 'met', 'ended', 'turned',
    'praised', 'passed', 'increased', 'taking', 'signed', 'told', 'attempt', 'find', 'come', 'directed',
    'claimed', 'asked', 'give', 'introduced', 'arrived', 'carried', 'defeated', 'becoming', 'complete',
    'suggested', 'entered', 'appointed', 'leaving', 'destroyed', 'winning', 'provide', 'proposed',
    'agreed', 'intended', 'running', 'supported', 'helped', 'married', 'awarded', 'create', 'appear',
    'planned', 'compared', 'captured', 'changed', 'done', 'issued', 'suffered', 'includes', 'leave',
    'plans', 'offered', 'fell', 'damaged', 'appears', 'act', 'ranked', 'ran', 'composed', 'revealed',
    'discovered', 'raised', 'takes', 'lived', 'launched', 'keep', 'contains', 'shown', 'attempted',
    'attacked', 'got', 'moving', 'referred', 'elected', 'selected', 'resulted', 'makes', 'defeat',
    'need', 'assigned', 'earned', 'commented', 'expected', 'know', 'covered', 'refused', 'declared',
    'giving', 'think', 'fighting', 'produce', 'pass', 'continue', 'presented', 'reduced', 'attended',
    'tried', 'accepted', 'stating', 'managed', 'showed', 'dropped', 'kept', 'begins', 'continues',
    'want', 'meant', 'conducted', 'starting', 'allowing', 'fall', 'hold', 'break', 'pay', 'transferred',
    'stop', 'becomes', 'owned', 'founded', 'concluded', 'remain', 'marked', 'observed', 'call',
    'featuring', 'write', 'paid', 'build', 'selling', 'broke', 'plays', 'sought', 'follow', 'designated',
    'struck', 'influenced', 'prevent', 'calling', 'meet', 'gained', 'nominated', 'promoted', 'say',
    'confirmed', 'proved', 'passing', 'explained', 'coming', 'serve', 'causing', 'says', 'join',
    'expressed', 'read', 'identified', 'tells', 'represented', 'defend', 'consisted', 'begin', 'argued',
    'fired', 'returning', 'bring', 'affected', 'laid', 'maintained', 'visited', 'comes', 'criticized',
    'develop', 'trying', 'avoid', 'claims', 'chosen', 'operated', 'offer', 'grew', 'stand', 'serving',
    'chose', 'opposed', 'participated', 'adopted', 'heard', 'escape', 'creating', 'flying', 'filmed',
    'regarded', 'perform', 'achieved', 'believe', 'claim', 'killing', 'retired', 'receive', 'granted',
    'rejected', 'improved', 'describes', 'expanded', 'fought', 'organized', 'caught', 'suggests',
    'acquired', 'gives', 'mentioned', 'kill', 'looking', 'controlled', 'finds', 'spread', 'search',
    'standing', 'singing', 'stay', 'containing', 'contributed', 'finish', 'provides', 'purchased',
    'accompanied', 'occur', 'occupied', 'protect', 'mounted', 'carry', 'consists', 'drawn', 'murder',
    'rise', 'defined', 'protected', 'engaged', 'receiving', 'calls', 'experienced', 'providing', 'holding',
    'hired', 'viewed', 'recognized', 'shared', 'developing', 'approved', 'try', 'gain', 'goes', 'knew',
    'save', 'strike', 'employed', 'injured', 'watched', 'enter', 'enjoyed', 'adding', 'renamed',
    'getting', 'declined', 'shaped', 'drew', 'converted', 'connected', 'allows', 'headed', 'missing',
    'cited', 'let', 'approached', 'turning', 'responded', 'planning', 'succeeded', 'collected',
    'learned', 'operating', 'carrying', 'showing', 'buried', 'credited', 'arranged', 'improve', 'seems',
    'producing', 'lasted', 'retained', 'applied', 'replace', 'indicated', 'delivered', 'stopped', 'filled',
    'contain', 'maintain', 'establish', 'watch', 'finding', 'threatened', 'bought', 'adapted', 'survived',
    'studied', 'writes', 'ruled', 'represent', 'reduce', 'voted', 'recalled', 'portrayed', 'arrested',
    'crossed', 'equipped', 'installed', 'invited', 'starts', 'interested', 'recommended', 'charged',
    'promote', 'admitted', 'driving', 'reading', 'occurs', 'describing', 'obtained', 'exist', 'certified',
    'accused', 'derived', 'wearing', 'assumed', 'committed', 'hosted', 'denied', 'sell', 'commanded',
    'bringing', 'tied', 'speaking', 'moves', 'finishing', 'incorporated', 'stayed', 'attributed', 'recovered',
    'breaking', 'emerged', 'serves', 'tell', 'driven', 'attracted', 'surviving', 'classified', 'stood',
    'separated', 'seemed', 'restored', 'hoped', 'requested', 'accept', 'raise', 'destroy', 'forming',
    'tries', 'crosses', 'determine', 'dismissed', 'convinced', 'ensure', 'attend', 'falling', 'fit',
    'starred', 'shoot', 'suggest', 'assist', 'meets', 'consider', 'seeing', 'fitted', 'operate',
    'encouraged', 'suffering', 'holds', 'lies', 'modified', 'painted', 'gone', 'believes', 'distributed',
    'attempting', 'looked', 'rescue', 'secured', 'depicted', 'dominated', 'continuing', 'trained',
    'representing', 'hope', 'releases', 'die', 'achieve', 'send', 'generated', 'deployed', 'gets', 'sees',
    'defended', 'discussed', 'treated', 'fly', 'executed', 'enters', 'require', 'resigned', 'reveals', 'talk',
    'watching', 'prevented', 'preferred', 'pushed', 'happened', 'facing', 'existed', 'lay', 'surrender',
    'learn', 'departed', 'linked', 'participate', 'exposed', 'pointed', 'learning', 'impressed', 'add',
    'taught', 'testing', 'speak', 'encountered', 'withdrew', 'upgraded', 'keeping', 'traveled', 'lose',
    'refers', 'criticised', 'indicate', 'compete', 'remove', 'handed', 'pitched', 'describe', 'forcing',
    'joining', 'acted', 'grown', 'pick', 'powered', 'asks', 'seem', 'survive', 'eliminated', 'covering',
    'seeking', 'arriving', 'helping', 'telling', 'understand', 'seek', 'resumed', 'assisted', 'defeating',
    'signing', 'submitted', 'understanding', 'citing', 'voiced', 'asking', 'buy', 'aimed', 'filed',
    'registered', 'liked', 'recognised', 'represents', 'replacing', 'reflected', 'completing', 'thinking',
    'suggesting', 'fled', 'sing', 'cancelled', 'rebuilt', 'wear', 'pulled', 'decides', 'escaped', 'argues',
    'walk', 'repair', 'saved', 'drove', 'hear', 'characterized', 'depending', 'earning', 'explains', 'fallen',
    'threw', 'demonstrated', 'arrive', 'spotted', 'evolved', 'feed', 'prepare', 'predicted', 'attained', 'fixed',
    'choose', 'perceived', 'remarked', 'waiting', 'visiting', 'demanded', 'enlisted', 'insisted', 'promised',
    'withdraw', 'demolished', 'feels', 'increases', 'heading', 'tend', 'believing', 'pursue', 'discovers',
    'engage', 'altered', 'affect', 'erected', 'indicating', 'prove', 'organised', 'permitted', 'acknowledged',
    'graduated', 'striking', 'realized', 'dressed', 'expand', 'celebrated', 'initiated', 'encounter',
    'requires', 'evacuated', 'originated', 'stationed', 'establishing', 'considering', 'cutting', 'connecting',
    'approaching', 'donated', 'placing', 'walking', 'lying', 'putting', 'indicates', 'decide', 'discuss',
    'supplied', 'identify']
    }